name: Build Android APK

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Debug APK
        run: gradle assembleDebug
        working-directory: ./Pos-main

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: Pos-main/app/build/outputs/apk/debug/app-debug.apk
          
